version: 0.2

phases:
  build:
    commands:
      - echo Invalidating Cloudfront cache
      - aws cloudfront create-invalidation --distribution-id $ROOT_S3_DISTRIBUTION_ID --paths "/*";
      - aws cloudfront create-invalidation --distribution-id $WWW_S3_DISTRIBUTION_ID --paths "/*";
